title: Project
pages: false
files:
  sortable: false
  max: null
  hide: false
  sanitize: true
  fields: null
  size: null
  width: null
  height: null
  fields:
    caption:
      label: Caption
      type: text
    videolink:
      label: Video Link
      type: url
fields:
  prevnext: prevnext
  title:
    label: Title
    type: title
    width: 3/4
  date:
    label: Date
    type: date
    format: YYYY
    required: true
    width: 1/4
  subtitle:
    label: Subtitle
    type: text
    width: 3/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  categories:
    label: Categories
    type: checkboxes
    options: field
    columns: 4
    field:
      page: ../
      name: categories
      separator: ,
  text:
    label: Description
    type: textarea
  medias:
    label: Medias
    type: images
